name: uhum
description: Fitness and Wellness App
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  google_fonts: ^4.0.3
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  shared_preferences: ^2.1.0
  firebase_core: ^2.10.0
  provider: ^6.0.5
  cloud_firestore: ^4.5.2
  lottie: ^2.3.2
  image_picker: ^0.8.7+4
  firebase_storage: ^11.1.1
  image_cropper: ^3.0.3
  flutter_spinkit: ^5.1.0
  path: ^1.8.2
  flutter_animate: ^4.1.1+1
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Splash/images/
    - assets/Home/images/
    - assets/Home/icons/
    - assets/Home/images1/
    - assets/Home/images2/
    - assets/Home/images3/
    - assets/Discover/images/
    - assets/Discover/icons/
    - assets/Discover/images1/
    - assets/Discover/images2/
    - assets/Discover/images3/
    - assets/Sharepage/images/bgpic.jpeg
    - assets/Sharepage/images/share.png
    - assets/Splash/images/bookcard.png
    - assets/OnBoarding/
    - assets/OnBoarding/ProfilePicture.jpg
    - assets/OnBoarding/Done.json
    - assets/OnBoarding/Builder.json
    - assets/Login/Login.json
    - assets/Logo/Logo.svg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
  #         style: italic
