name: uhum
description: Fitness and Wellness App
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  google_fonts: ^4.0.3
  firebase_auth: ^4.2.10
  google_sign_in: ^6.0.2
  shared_preferences: ^2.0.18
  firebase_core: ^2.7.1
  provider: ^6.0.5
  cloud_firestore: ^4.4.4
  lottie: ^2.3.0
  image_picker: ^0.8.7
  firebase_storage: ^11.0.15
  image_cropper: ^3.0.1
  flutter_spinkit: ^5.1.0
  path: ^1.8.2
  #flutter_launcher_name: ^0.0.1

dev_dependencies:

flutter_launcher_name:
  name: "AHUM"

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Splash/images/
    - assets/Home/images/
    - assets/Home/icons/
    - assets/Home/images1/
    - assets/Home/images2/
    - assets/Home/images3/
    - assets/Discover/images/
    - assets/Discover/icons/
    - assets/Discover/images1/
    - assets/Discover/images2/
    - assets/Discover/images3/
    - assets/Sharepage/images/bgpic.jpeg
    - assets/Sharepage/images/share.png
    - assets/Splash/images/bookcard.png
    - assets/OnBoarding/
    - assets/OnBoarding/ProfilePicture.jpg
    - assets/OnBoarding/Done.json
    - assets/OnBoarding/Builder.json
    - assets/Login/Login.json

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
  #         style: italic