export 'package:flutter/material.dart';
export 'package:lottie/lottie.dart';
export 'package:provider/provider.dart';
export 'package:uhum/Homepage.dart';
export 'package:uhum/Provider/OnBoardingScreen/on_boarding_provider.dart';
export 'package:uhum/Screens/GlobalWidgets/background_widget.dart';
export 'package:uhum/Screens/LoginScreen/login_screen.dart';
export 'package:uhum/Screens/OnBoardingScreen/OnBoardingScreen.dart';
export 'package:uhum/Screens/RegisterScreen/register_screen.dart';
